// Shared UI primitives. Feature areas use these; they do not edit this file (ask the orchestrator instead).
import { useEffect, useRef, type ReactNode } from 'react';
import { Icon } from './Icon';
import { useStore } from '../store/store';
import { clamp } from '../lib/format';
import { QuickAddButton } from './QuickAdd';

/** Light vibration on supported phones. */
export function haptic(ms = 10) {
  try {
    navigator.vibrate?.(ms);
  } catch {
    /* not supported */
  }
}

/** Score ring. value 0..1. */
export function Ring({ value, size = 96, stroke = 9, children, color = 'var(--accent)' }: {
  value: number; size?: number; stroke?: number; children?: ReactNode; color?: string;
}) {
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  const v = clamp(value, 0, 1);
  return (
    <div style={{ position: 'relative', width: size, height: size, flex: 'none' }}>
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} aria-hidden="true">
        <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="var(--surface-2)" strokeWidth={stroke} />
        <circle
          cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={stroke} strokeLinecap="round"
          strokeDasharray={c} strokeDashoffset={c * (1 - v)} transform={`rotate(-90 ${size / 2} ${size / 2})`}
          style={{ transition: 'stroke-dashoffset .4s var(--ease)' }}
        />
      </svg>
      <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', textAlign: 'center' }}>{children}</div>
    </div>
  );
}

/** Horizontal progress bar. value 0..1 (over 1 shows the over state when `overIsBad`). */
export function Bar({ value, ok, overIsBad }: { value: number; ok?: boolean; overIsBad?: boolean }) {
  const cls = overIsBad && value > 1 ? 'bar over' : ok || value >= 1 ? 'bar ok' : 'bar';
  return (
    <div className={cls} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(value * 100)}>
      <i style={{ width: `${clamp(value, 0, 1) * 100}%` }} />
    </div>
  );
}

export function Segmented<T extends string>({ value, options, onChange, label }: {
  value: T; options: { value: T; label: string }[]; onChange: (v: T) => void; label: string;
}) {
  return (
    <div className="seg" role="group" aria-label={label}>
      {options.map((o) => (
        <button key={o.value} type="button" aria-pressed={o.value === value} onClick={() => onChange(o.value)}>
          {o.label}
        </button>
      ))}
    </div>
  );
}

/**
 * Title row for a screen. Shows a back button when `back` is true.
 * Main-tab headers (no back button) also get the quick-add (+) on the right, unless `quickAdd` is false.
 */
export function ScreenHeader({ title, back, right, quickAdd }: { title: string; back?: boolean; right?: ReactNode; quickAdd?: boolean }) {
  const goBack = useStore((s) => s.back);
  const showQuick = quickAdd ?? !back;
  return (
    <header className="screen-head">
      {back && (
        <button className="icon-btn" type="button" onClick={goBack} aria-label="Back">
          <Icon name="back" />
        </button>
      )}
      <h1>{title}</h1>
      {right}
      {showQuick && <QuickAddButton />}
    </header>
  );
}

export function Empty({ icon = 'info', title, children }: { icon?: string; title: string; children?: ReactNode }) {
  return (
    <div className="empty">
      <Icon name={icon} />
      <strong>{title}</strong>
      {children && <div className="small">{children}</div>}
    </div>
  );
}

export function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="field">
      <span>{label}</span>
      {children}
    </label>
  );
}

/** Keeps the latest callback in a ref (for timers). */
export function useLatest<T>(v: T) {
  const r = useRef(v);
  useEffect(() => {
    r.current = v;
  });
  return r;
}
